---
deployment:
  tasks:
    - export DEPLOYPATH=/public_html/
    - export REPOPATH=/cprepo
    - echo "Deployment started at $(date)" > $DEPLOYPATH/deployment-log.txt
    - /bin/cp -R $REPOPATH/back-end/dist/* $DEPLOYPATH
    - /bin/cp -R $REPOPATH/back-end/uploads $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp $REPOPATH/back-end/server.js $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/back-end/config $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/back-end/routes $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/back-end/utils $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/back-end/models $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/back-end/controllers $DEPLOYPATH/api/
    - /bin/cp $REPOPATH/back-end/package.json $DEPLOYPATH/api/
    - /bin/cp $REPOPATH/back-end/.env $DEPLOYPATH/api/
    - cd $DEPLOYPATH/api && npm install --production
    - echo "Deployment completed at $(date)" >> $DEPLOYPATH/deployment-log.txt