---
deployment:
  tasks:
    - export DEPLOYPATH=/home/latestfi/public_html/
    - export REPOPATH=/home/latestfi/repositories/Latest-Fitness-gym/back-end
    - /bin/cp -R $REPOPATH/dist/* $DEPLOYPATH
    - /bin/cp -R $REPOPATH/uploads $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp $REPOPATH/server.js $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/config $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/routes $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/utils $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/models $DEPLOYPATH/api/
    - /bin/cp -R $REPOPATH/controllers $DEPLOYPATH/api/
    - /bin/cp $REPOPATH/package.json $DEPLOYPATH/api/
    - /bin/cp $REPOPATH/.env $DEPLOYPATH/api/
    - cd $DEPLOYPATH/api && npm install --production
